export const TIMESLOTSSTART = [
  { value: 1, text: '12 AM - 1 AM', booked: false },
  { value: 2, text: '1 AM - 2 AM', booked: false },
  { value: 3, text: '2 AM - 3 AM', booked: false },
  { value: 4, text: '3 AM - 4 AM', booked: false },
  { value: 5, text: '4 AM - 5 AM', booked: false },
  { value: 6, text: '5 AM - 6 AM', booked: false },
  { value: 7, text: '6 AM - 7 AM', booked: false },
  { value: 8, text: '7 AM - 8 AM', booked: false },
  { value: 9, text: '8 AM - 9 AM', booked: false },
  { value: 10, text: '9 AM - 10 AM', booked: false },
  { value: 11, text: '10 AM - 11 AM', booked: false },
  { value: 12, text: '11 AM - 12 Noon', booked: false },
  { value: 13, text: '12 Noon - 1 PM', booked: false },
  { value: 14, text: '1 PM - 2 PM', booked: false },
  { value: 15, text: '2 PM - 3 PM', booked: false },
  { value: 16, text: '3 PM - 4 PM', booked: false },
  { value: 17, text: '4 PM - 5 PM', booked: false },
  { value: 18, text: '5 PM - 6 PM', booked: false },
  { value: 19, text: '6 PM - 7 PM', booked: false },
  { value: 20, text: '7 PM - 8 PM', booked: false },
  { value: 21, text: '8 PM - 9 PM', booked: false },
  { value: 22, text: '9 PM - 10 PM', booked: false },
  { value: 23, text: '10 PM - 11 PM', booked: false },
  { value: 24, text: '11 PM - 12 Midnight', booked: false }
]
